name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          TOKENGH: ${{ secrets.TOKENGH }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>Dugnychon</username><password>${TOKENGH}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/Dugnychon/lastfm-api